/* =============================================================
   Mac Sutherland - Portfolio · interactions & content
   -------------------------------------------------------------
   Driven by the five real brands below. Images live in
   assets/img/<slug>/ (cover.jpg + 01..10.jpg), generated by
   build-assets.sh. Metrics/copy are editable placeholders -
   swap them for your real numbers any time.
   ============================================================= */

/* media data comes from assets/media-data.js (window.MEDIA), generated by build_media.py.
   Shape: MEDIA[slug] = { name, cover, collections:[{ label, slug, images:[], videos:[{src,poster}] }] } */
const MEDIA = window.MEDIA || {};
const cover       = (slug) => (MEDIA[slug] && MEDIA[slug].cover) || `assets/img/${slug}/cover.jpg`;
const collections = (slug) => (MEDIA[slug] && MEDIA[slug].collections) || [];
const allImages   = (slug) => collections(slug).flatMap(c => c.images);
const allVideos   = (slug) => collections(slug).flatMap(c => c.videos);

/* ---- CASE STUDIES (real brands) ----------------------------- */
const CASES = [
  {
    slug: 'north-kiteboarding',
    bannerPos: 'center 20%',
    tag: 'Global Brand · Social + Content',
    name: 'North Kiteboarding',
    role: 'Social Media & Content Manager · 2022–2023',
    badge: 'North Kiteboarding, Global Social & Content',
    metrics: [['76K→80K', 'Instagram (non-launch)'], ['14K', 'YouTube subscribers'], ['3', 'Red Bull / PWA events']],
    challenge: 'I needed to keep the audience growing and engaged for one of the world\'s leading kiteboarding brands through a seven-month "business as usual" stretch, with no new product launches or campaigns to lean on.',
    work: 'I owned content strategy, production, copywriting, scheduling and community management across Instagram, Facebook and YouTube, working closely with the Global Marketing Manager. I grew the audience through creative storytelling, international athlete moments and user-generated content, and I captured content on the ground at Red Bull King of the Air, Red Bull Megaloop and the Cold Hawaii PWA World Cup. I was promoted into the role within 12 months.'
  },
  {
    slug: 'north-foils',
    tag: 'Global Brand · Channel Growth',
    name: 'North Foils',
    role: 'Social Media & Content Manager · 2022–2023',
    badge: 'North Foils, Channel Growth',
    metrics: [['+225%', 'Instagram growth'], ['1.4K→4.58K', 'Followers'], ['5.5K', 'YouTube subscribers']],
    challenge: 'When I took it over, North Foils\' Instagram sat at around 1,400 followers, a small early-stage community, and there was a packed calendar of product launches to support.',
    work: 'I built a content strategy around high-quality visuals, engaging copy and consistent posting, leaning into industry trends and user-generated content to create a real sense of community. I grew Instagram to 4,580 followers (a jump of 225%) and YouTube to 5.5K subscribers, while delivering launches including Nova, Seek Air, SF Series, Open Sessions and the Sonar Rider Guide.'
  },
  {
    slug: 'surf-life-saving-nz',
    bannerPos: 'center 15%',
    gridImages: [
      'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/001.jpg',
      'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/013.jpg',
      'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/037.jpg',
      'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/030.jpg',
      'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/025.jpg',
      'assets/img/surf-life-saving-nz/bp-irb-championships-2026/004.jpg',
      'assets/img/surf-life-saving-nz/bp-irb-championships-2026/016.jpg',
      'assets/img/surf-life-saving-nz/bp-irb-championships-2026/028.jpg',
      'assets/img/surf-life-saving-nz/international-surf-rescue-challenge-2025/004.jpg',
    ],
    tag: 'Purpose-led · Campaign + Community',
    name: 'Surf Life Saving NZ',
    role: 'Digital Marketing Lead · 2025–Present',
    badge: 'Surf Life Saving New Zealand',
    metrics: [['+5,000', 'Followers in 6 months'], ['#1', 'Top posts in channel history'], ['5', 'National & int\'l events']],
    challenge: 'I lead digital for a national, purpose-led organisation, which means juggling public safety, fundraising, volunteer recruitment, education and major sporting events all at once, across a lot of channels.',
    work: 'I own content strategy and production across Facebook, Instagram, TikTok, LinkedIn and YouTube, plus paid media on Meta and Google, the monthly newsletter, and the website, SEO and GA4 reporting. In six months I grew the organisational Instagram by 3,000 followers and the Surf Sports channels by another 2,000, delivered the highest-performing posts in the channel\'s history, and directed content across five national and international surf-lifesaving events.'
  },
  {
    slug: 'surfr-app',
    banner: 'assets/img/surfr-app/cold-hawaii-event/002.jpg',
    gridImages: [
      'assets/img/surfr-app/cold-hawaii-event/008.jpg',
      'assets/img/surfr-app/cold-hawaii-event/002.jpg',
      'assets/img/surfr-app/cold-hawaii-event/004.jpg',
      'assets/img/surfr-app/cold-hawaii-event/009.jpg',
      'assets/img/surfr-app/cold-hawaii-event/006.jpg',
    ],
    tag: 'Sport-Tech Startup · Social Lead',
    name: 'The Surfr App',
    role: 'Social Media & Content Lead · 2024',
    badge: 'The Surfr App, Founder-led Social',
    metrics: [['1:1', 'Reported to founder'], ['4 ch.', 'IG · FB · TikTok · YT'], ['Global', 'Athlete network']],
    challenge: 'A global surf-performance tech startup that needed brand awareness, app engagement and community growth, all built from a small base and reporting straight to the founder.',
    work: 'I developed and ran a multi-channel content strategy across Instagram, Facebook, TikTok and YouTube, owning the planning, copywriting, scheduling and a consistent brand voice. I led athlete, ambassador and influencer partnerships and user-generated content, looked after community engagement and app-store reputation, and captured content at international kiteboarding events to promote new features and updates.'
  },
  {
    slug: 'bike-storage',
    tag: 'B2B + B2C · Full-Funnel Marketing',
    name: 'The Bike Storage Company',
    role: 'Marketing Manager · 2023–2025',
    badge: 'The Bike Storage Company, London',
    metrics: [['£310K', 'Incremental revenue'], ['3×', 'Inbound leads'], ['+179K', 'Ad clicks YoY']],
    challenge: 'I owned marketing end to end for a market-leading B2B and B2C business, covering digital acquisition, content, paid media, SEO, email and brand, all against ambitious revenue and lead-gen targets.',
    work: 'I overhauled the paid and organic strategy to deliver £310,000 in incremental e-commerce revenue and 1,860 extra conversions in 12 months. I rebuilt the Google Ads accounts from the ground up (179,000 more clicks year on year at a lower cost per acquisition), tripled inbound leads through SEO, UX and CRO, and ran multi-channel paid media across Google, LinkedIn and Microsoft Ads.'
  }
];

/* ---- SERVICES ----------------------------------------------- */
const SERVICES = [
  ['Content Strategy', 'Pillars, calendars, and platform-native creative direction that keeps a brand showing up like it belongs.', 'M4 6h16M4 12h10M4 18h7'],
  ['Paid Social', 'Meta, TikTok and YouTube ad programmes, from account structure and creative testing to scaling spend while holding ROAS.', 'M3 17l6-6 4 4 7-8M21 7v5M21 7h-5'],
  ['Community Management', 'Daily presence, DMs, and ambassador programs that turn followers into a crew.', 'M16 19a4 4 0 0 0-8 0M12 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6'],
  ['Creator & Influencer', 'Sourcing, briefing, and whitelisting athletes and creators who actually live the sport.', 'M12 2l2.4 6.9H22l-6 4.3 2.3 6.8-6.3-4.4-6.3 4.4L7.9 13l-6-4.3h7.6z'],
  ['Analytics & Reporting', 'GA4, platform insights, and clean dashboards that connect content to revenue.', 'M4 19V5m4 14V9m4 10V12m4 7V7m4 12V4'],
  ['Campaign Management', 'Launches handled end to end, from concept and shoot coordination through rollout and the post-mortem.', 'M5 3v18M5 5h12l-2 3 2 3H5'],
];

/* ---- TOP-PERFORMING POSTS (real Instagram posts, stats pulled live) ----
   Ordered best-performing first. Thumbnails are the real post images, downloaded
   and stored locally in assets/img/posts/ (IG CDN URLs expire). Cards link to the post. */
const POSTS = [
  { handle: '@surflifesavingnz', likes: '4.4K', cmts: '20', kind: 'Carousel', date: 'Mar 2026', caption: 'Day two of IRB racing, and Sunset Beach grabbed gold. 🥇', thumb: 'assets/img/posts/DWaovM5jwjR.jpg', url: 'https://www.instagram.com/p/DWaovM5jwjR/' },
  { handle: '@northkiteboarding', likes: '2.6K', cmts: '28', kind: 'Reel', date: 'Jan 2023', caption: 'Our Iceland film with Mystic, Dysfunctional Beauty. ❄️', thumb: 'assets/img/posts/CnmzDAAJv5E.jpg', url: 'https://www.instagram.com/p/CnmzDAAJv5E/' },
  { handle: '@northkiteboarding', likes: '2.0K', cmts: '34', kind: 'Reel', date: 'Feb 2023', caption: "Jesse Richman at Jaws, hitting 40mph on one of the Pacific's heaviest waves.", thumb: 'assets/img/posts/CoHMHZPux4q.jpg', url: 'https://www.instagram.com/p/CoHMHZPux4q/' },
  { handle: '@northkiteboarding', likes: '1.3K', cmts: '10', kind: 'Carousel', date: 'Jun 2023', caption: 'Glaciers, icebergs and a serious dose of humble. 🇮🇸', thumb: 'assets/img/posts/CuBtjRRv6zT.jpg', url: 'https://www.instagram.com/p/CuBtjRRv6zT/' },
  { handle: '@northkiteboarding', likes: '1.1K', cmts: '15', kind: 'Post', date: 'Feb 2023', caption: 'The Carve in action with Jesse Richman in Maui.', thumb: 'assets/img/posts/CoJ1EFMO_ps.jpg', url: 'https://www.instagram.com/p/CoJ1EFMO_ps/' },
  { handle: '@northkiteboarding', likes: '1.1K', cmts: '7', kind: 'Post', date: 'Jun 2023', caption: 'Completely obsessed with pushing it further.', thumb: 'assets/img/posts/CuH7gwUJYt0.jpg', url: 'https://www.instagram.com/p/CuH7gwUJYt0/' },
  { handle: '@surflifesavingnz', likes: '981', cmts: '2', kind: 'Carousel', date: 'Mar 2026', caption: 'Day one at Ōhope for the 2026 Aon Nationals. ☀️', thumb: 'assets/img/surf-life-saving-nz/2026-surf-life-saving-championships/015.jpg', url: 'https://www.instagram.com/p/DVfkHqOj6Wu/' },
  { handle: '@northkiteboarding', likes: '939', cmts: '4', kind: 'Carousel', date: 'May 2023', caption: 'Megaloops on the 10m Orbit. Time to send it.', thumb: 'assets/img/posts/CsLYR0EP8Wh.jpg', url: 'https://www.instagram.com/p/CsLYR0EP8Wh/' },
  { handle: '@northkiteboarding', likes: '831', cmts: '7', kind: 'Carousel', date: 'Jul 2023', caption: 'For the seekers. Something is coming.', thumb: 'assets/img/north-kiteboarding/big-air-2024/006.jpg', url: 'https://www.instagram.com/p/Cu_m9iHvH3e/' },
  { handle: '@northkiteboarding', likes: '830', cmts: '5', kind: 'Post', date: 'Jan 2023', caption: 'Completely in sync with the ocean.', thumb: 'assets/img/posts/CnRHXllpE1P.jpg', url: 'https://www.instagram.com/p/CnRHXllpE1P/' },
  { handle: '@northkiteboarding', likes: '770', cmts: '6', kind: 'Carousel', date: 'Sep 2023', caption: 'Camille Delannoy lighting it up in the Philippines.', thumb: 'assets/img/posts/Cw4X7q6vJtG.jpg', url: 'https://www.instagram.com/p/Cw4X7q6vJtG/' },
  { handle: '@surflifesavingnz', likes: '670', cmts: '2', kind: 'Carousel', date: 'Mar 2026', caption: 'That is a wrap. 1,400 athletes and one champion, Omanu. 💛', thumb: 'assets/img/posts/DVnbLbJj30t.jpg', url: 'https://www.instagram.com/p/DVnbLbJj30t/' },
  { handle: '@surflifesavingnz', likes: '508', cmts: '1', kind: 'Post', date: 'Mar 2026', caption: 'Omanu SLSC take the national club title.', thumb: 'assets/img/posts/DVpx8BGDzKN.jpg', url: 'https://www.instagram.com/p/DVpx8BGDzKN/' },
  { handle: '@northkiteboarding', likes: '500', cmts: '8', kind: 'Carousel', date: 'May 2023', caption: 'Tom Rocco Bridge going freestyle in Taiba. 📷 Diego Correia', thumb: 'assets/img/north-kiteboarding/big-air-2024/009.jpg', url: 'https://www.instagram.com/p/Cs3JAinPeeD/' },
  { handle: '@surflifesavingnz', likes: '447', cmts: '0', kind: 'Post', date: 'Mar 2026', caption: 'Day three highlights from Ōhope.', thumb: 'assets/img/posts/DVmsyIjDw4h.jpg', url: 'https://www.instagram.com/p/DVmsyIjDw4h/' },
  { handle: '@surflifesavingnz', likes: '219', cmts: '0', kind: 'Post', date: 'Jun 2026', caption: 'Welcome to the whānau, Fulton Hogan. 💛🩵', thumb: 'assets/img/posts/DZ9TINUmxen.jpg', url: 'https://www.instagram.com/p/DZ9TINUmxen/' },
  { handle: '@surflifesavingnz', likes: '197', cmts: '3', kind: 'Post', date: 'Jun 2026', caption: 'Celebrating our volunteers for National Volunteer Week.', thumb: 'assets/img/posts/DZuEFmlDgAE.jpg', url: 'https://www.instagram.com/p/DZuEFmlDgAE/' },
];

/* ============================================================
   RENDER
   ============================================================ */
const el = (html) => { const t = document.createElement('template'); t.innerHTML = html.trim(); return t.content.firstElementChild; };

/* -- Work / masonry: interleave brands so the gallery mixes work -- */
const workGrid = document.getElementById('workGrid');

// Each brand contributes a spread of photo teaser tiles (videos live in the modal gallery).
// A brand can set `teaser` (a collection slug) to source its grid tiles from a specific
// campaign — handy for brands whose full set is graphics-heavy.
// GRID_TILES weights how many tiles each brand gets: lead with the strongest imagery.
const GRID_TILES = {
  'north-kiteboarding': 8,
  'north-foils': 8,
  'surf-life-saving-nz': 9,
  'surfr-app': 5,
  'bike-storage': 2,
};
const piles = CASES.map((c, ci) => {
  // explicit hand-picked grid imagery wins (strongest shots, no weak auto-samples)
  if (c.gridImages && c.gridImages.length) return c.gridImages.map(src => ({ ci, src }));
  let imgs = allImages(c.slug);
  if (c.teaser) {
    const col = collections(c.slug).find(x => x.slug === c.teaser);
    if (col && col.images.length) imgs = col.images;
  }
  // evenly sample images across the set so the teaser feels representative
  const want = Math.min(GRID_TILES[c.slug] || 5, imgs.length);
  const step = Math.max(1, Math.floor(imgs.length / want));
  const picks = [];
  for (let i = 0, n = 0; i < imgs.length && n < want; i += step, n++) picks.push({ ci, src: imgs[i] });
  return picks.slice(0, want);
});
// round-robin interleave so the grid mixes brands like a contact sheet
const maxLen = Math.max(...piles.map(p => p.length));
const tiles = [];
for (let k = 0; k < maxLen; k++) piles.forEach(p => { if (p[k]) tiles.push(p[k]); });

tiles.forEach(t => {
  const c = CASES[t.ci];
  const headline = c.metrics[0];
  workGrid.appendChild(el(`
    <button class="tile reveal" data-case="${t.ci}" aria-label="Open case study: ${c.name}">
      <span class="tile__rest">${c.name}</span>
      <div class="tile__media">
        <img class="tile__img" src="${t.src}" alt="${c.name} social content" loading="lazy" />
      </div>
      <div class="tile__cap">
        <div class="tile__tag">${c.tag.split('·')[0].trim()}</div>
        <div class="tile__name">${c.name}</div>
        <div class="tile__metric"><b>${headline[0]}</b> ${headline[1]}</div>
      </div>
    </button>`));
});

/* -- Services -- */
const svcGrid = document.getElementById('svcGrid');
SERVICES.forEach(([title, desc, path]) => {
  svcGrid.appendChild(el(`
    <article class="svc reveal">
      <div class="svc__ico"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${path}"/></svg></div>
      <h3>${title}</h3>
      <p>${desc}</p>
    </article>`));
});

/* -- Top-performing posts carousel -- */
const postsTrack = document.getElementById('postsTrack');
POSTS.forEach(p => {
  postsTrack.appendChild(el(`
    <a class="post reveal" href="${p.url}" target="_blank" rel="noopener" aria-label="Open ${p.handle} post on Instagram">
      <div class="post__bar">
        <span class="post__avatar" aria-hidden="true">${p.handle[1].toUpperCase()}</span>
        <span class="post__handle">${p.handle}</span>
        <span class="plat">${p.kind}</span>
      </div>
      <div class="post__media"><img src="${p.thumb}" alt="${p.handle}: ${p.caption}" loading="lazy" /></div>
      <div class="post__cap">${p.caption}</div>
      <div class="post__foot">
        <span>❤ ${p.likes}</span>
        <span>💬 ${p.cmts}</span>
        <span class="post__date">${p.date}</span>
      </div>
    </a>`));
});

/* carousel scroll controls (buttons + drag) */
const postsCarousel = document.getElementById('postsCarousel');
const scrollByCards = (dir) => {
  const card = postsTrack.querySelector('.post');
  const amount = card ? (card.offsetWidth + 16) * 1.5 : 360;
  postsCarousel.scrollBy({ left: dir * amount, behavior: 'smooth' });
};
document.getElementById('postsPrev').addEventListener('click', () => scrollByCards(-1));
document.getElementById('postsNext').addEventListener('click', () => scrollByCards(1));
// drag-to-scroll (pointer), without hijacking card clicks
let dragX = 0, dragL = 0, dragging = false, moved = false;
postsCarousel.addEventListener('pointerdown', e => { dragging = true; moved = false; dragX = e.pageX; dragL = postsCarousel.scrollLeft; });
postsCarousel.addEventListener('pointermove', e => {
  if (!dragging) return;
  const dx = e.pageX - dragX;
  if (Math.abs(dx) > 6) moved = true;
  postsCarousel.scrollLeft = dragL - dx;
});
const endDrag = () => { dragging = false; };
postsCarousel.addEventListener('pointerup', endDrag);
postsCarousel.addEventListener('pointerleave', endDrag);
// suppress the click that follows a drag so it doesn't open Instagram accidentally
postsCarousel.addEventListener('click', e => { if (moved) { e.preventDefault(); moved = false; } }, true);

/* ============================================================
   CASE STUDY MODAL (with image gallery)
   ============================================================ */
const modal = document.getElementById('modal');
const mHero = document.getElementById('mHero');
let lastFocused = null;
let currentCollections = [];   // [{label, items:[{type,src,poster}]}] for the open brand
let galleryItems = [];         // the items the lightbox is currently navigating

function openCase(i){
  const c = CASES[i];
  lastFocused = document.activeElement;
  mHero.style.backgroundImage = `linear-gradient(180deg, transparent 50%, rgba(0,0,0,.6)), url("${c.banner || cover(c.slug)}")`;
  mHero.style.backgroundPosition = c.bannerPos || 'center';
  document.getElementById('mBadge').textContent = c.badge;
  document.getElementById('mRole').textContent = c.role;
  document.getElementById('mTitle').textContent = c.name;
  document.getElementById('mChallenge').textContent = c.challenge;
  document.getElementById('mWork').textContent = c.work;

  const mm = document.getElementById('mMetrics');
  mm.innerHTML = '';
  c.metrics.forEach(([v, l]) => {
    const node = el(`<div class="mstat"><div class="v"><span></span></div><div class="l">${l}</div></div>`);
    mm.appendChild(node);
    countUpText(node.querySelector('.v span'), v);   // count-up each metric on open
  });

  // Build campaign collections; each becomes a labelled, lightbox-scoped sub-gallery
  currentCollections = collections(c.slug).map(col => ({
    label: col.label,
    items: [
      ...col.videos.map(v => ({ type: 'video', src: v.src, poster: v.poster })),
      ...col.images.map(src => ({ type: 'image', src }))
    ]
  })).filter(col => col.items.length);

  const mg = document.getElementById('mGallery');
  mg.innerHTML = '';
  currentCollections.forEach((col, colIdx) => {
    const nImg = col.items.filter(i => i.type === 'image').length;
    const nVid = col.items.length - nImg;
    const count = [nImg && `${nImg} photo${nImg > 1 ? 's' : ''}`, nVid && `${nVid} video${nVid > 1 ? 's' : ''}`].filter(Boolean).join(' · ');
    const section = el(`
      <section class="collection">
        <div class="gallery-head"><h4>${col.label}</h4><span class="cnt">${count}</span></div>
        <div class="modal__gallery"></div>
      </section>`);
    const grid = section.querySelector('.modal__gallery');
    col.items.forEach((it, gi) => {
      const thumb = it.type === 'video' ? it.poster : it.src;
      grid.appendChild(el(`
        <button class="gitem ${it.type === 'video' ? 'gitem--video' : ''}" data-col="${colIdx}" data-gi="${gi}" aria-label="View ${it.type}">
          <img src="${thumb}" alt="${c.name}, ${col.label} ${it.type}" loading="lazy" />
        </button>`));
    });
    mg.appendChild(section);
  });

  modal.classList.add('open');
  modal.setAttribute('aria-hidden', 'false');
  document.body.style.overflow = 'hidden';
  modal.querySelector('.modal__panel').scrollTop = 0;
  modal.querySelector('.modal__close').focus();
}
function closeCase(){
  modal.classList.remove('open');
  modal.setAttribute('aria-hidden', 'true');
  document.body.style.overflow = '';
  if (lastFocused) lastFocused.focus();
}
workGrid.addEventListener('click', e => {
  const t = e.target.closest('[data-case]');
  if (t) openCase(+t.dataset.case);
});
modal.addEventListener('click', e => { if (e.target.hasAttribute('data-close')) closeCase(); });
document.addEventListener('keydown', e => { if (e.key === 'Escape' && modal.classList.contains('open') && !lightbox.classList.contains('open')) closeCase(); });

// open lightbox from a gallery thumbnail - scoped to its campaign collection
document.getElementById('mGallery').addEventListener('click', e => {
  const b = e.target.closest('[data-gi]');
  if (!b) return;
  const col = currentCollections[+b.dataset.col];
  if (!col) return;
  galleryItems = col.items;
  openLightbox(+b.dataset.gi);
});

/* ============================================================
   LIGHTBOX - images + video playback, prev/next, keyboard
   ============================================================ */
const lightbox = document.getElementById('lightbox');
const lbStage = document.getElementById('lbStage');
const lbCount = document.getElementById('lbCount');
let lbIndex = 0;

function renderLB(){
  const it = galleryItems[lbIndex];
  if (!it) return;
  lbStage.innerHTML = it.type === 'video'
    ? `<video src="${it.src}" poster="${it.poster}" controls autoplay playsinline></video>`
    : `<img src="${it.src}" alt="Gallery item ${lbIndex + 1}" />`;
  lbCount.textContent = `${lbIndex + 1} / ${galleryItems.length}`;
}
function openLightbox(i){
  if (!galleryItems.length) return;
  lbIndex = (i + galleryItems.length) % galleryItems.length;
  renderLB();
  lightbox.classList.add('open');
  lightbox.setAttribute('aria-hidden', 'false');
}
function closeLightbox(){
  lightbox.classList.remove('open');
  lightbox.setAttribute('aria-hidden', 'true');
  lbStage.innerHTML = '';   // stop any playing video
}
function stepLB(d){ openLightbox(lbIndex + d); }

lightbox.addEventListener('click', e => {
  if (e.target.hasAttribute('data-lb-close') || e.target === lightbox) return closeLightbox();
  if (e.target.closest('[data-lb-prev]')) return stepLB(-1);
  if (e.target.closest('[data-lb-next]')) return stepLB(1);
});
document.addEventListener('keydown', e => {
  if (!lightbox.classList.contains('open')) return;
  if (e.key === 'Escape') closeLightbox();
  else if (e.key === 'ArrowLeft') stepLB(-1);
  else if (e.key === 'ArrowRight') stepLB(1);
});

/* ============================================================
   NAV - scrolled state + mobile toggle
   ============================================================ */
const nav = document.getElementById('nav');
const onScroll = () => {
  nav.classList.toggle('scrolled', window.scrollY > 24);
  document.getElementById('toTop').classList.toggle('show', window.scrollY > 600);
};
window.addEventListener('scroll', onScroll, { passive: true });
onScroll();

const navLinks = document.getElementById('navLinks');
const navToggle = document.getElementById('navToggle');
navToggle.addEventListener('click', () => {
  const open = navLinks.classList.toggle('open');
  navToggle.setAttribute('aria-expanded', open);
});
navLinks.addEventListener('click', e => { if (e.target.tagName === 'A') navLinks.classList.remove('open'); });

document.getElementById('toTop').addEventListener('click', () =>
  window.scrollTo({ top: 0, behavior: 'smooth' }));

/* ============================================================
   REVEAL ON SCROLL
   ============================================================ */
const io = new IntersectionObserver((entries) => {
  entries.forEach(en => { if (en.isIntersecting){ en.target.classList.add('in'); io.unobserve(en.target); } });
}, { threshold: 0.12, rootMargin: '0px 0px -40px 0px' });
document.querySelectorAll('.reveal').forEach(n => io.observe(n));

/* ============================================================
   CONTACT FORM (demo - no backend yet)
   ============================================================ */
const form = document.getElementById('contactForm');
form.addEventListener('submit', e => {
  e.preventDefault();
  const note = document.getElementById('formNote');
  if (!form.checkValidity()) { note.textContent = 'Please fill in all fields.'; note.style.color = 'var(--sunline)'; return; }
  note.textContent = 'Thanks. This is a demo, so connect a form backend to actually receive it.';
  note.style.color = 'var(--surf)';
  form.reset();
});

document.getElementById('year').textContent = new Date().getFullYear();

/* ============================================================
   HERO PARALLAX + STATS COUNT-UP (subtle scroll animation)
   ============================================================ */
const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

/* -- Faint scroll-progress accent across the top -- */
const scrollProgress = document.getElementById('scrollProgress');
if (scrollProgress) {
  const updateProgress = () => {
    const docH = document.documentElement.scrollHeight - window.innerHeight;
    scrollProgress.style.transform = `scaleX(${docH > 0 ? window.scrollY / docH : 0})`;
  };
  window.addEventListener('scroll', updateProgress, { passive: true });
  window.addEventListener('resize', updateProgress, { passive: true });
  updateProgress();
}

/* -- Generic count-up: animates the last number in a string, keeping decimals,
      thousands separators and any surrounding text (e.g. "76K→80K", "£310K", "+5,000"). -- */
function countUpText(elTarget, finalStr, dur = 1400){
  const tokens = String(finalStr).match(/[\d,]*\.?\d+/g);
  if (reduceMotion || !tokens) { elTarget.textContent = finalStr; return; }
  const token = tokens[tokens.length - 1];
  const idx = String(finalStr).lastIndexOf(token);
  const pre = String(finalStr).slice(0, idx);
  const suf = String(finalStr).slice(idx + token.length);
  const hasComma = token.includes(',');
  const decimals = token.includes('.') ? token.split('.')[1].length : 0;
  const target = parseFloat(token.replace(/,/g, ''));
  const fmt = (v) => hasComma
    ? Number(v.toFixed(decimals)).toLocaleString('en-US', { minimumFractionDigits: decimals, maximumFractionDigits: decimals })
    : v.toFixed(decimals);
  const start = performance.now();
  const stepFn = (now) => {
    const p = Math.min(1, (now - start) / dur);
    const eased = 1 - Math.pow(1 - p, 3);
    elTarget.textContent = pre + fmt(target * eased) + suf;
    if (p < 1) requestAnimationFrame(stepFn);
  };
  requestAnimationFrame(stepFn);
}

/* -- Hero parallax: waves, glow and headline drift/fade at different rates -- */
if (!reduceMotion) {
  const hero       = document.querySelector('.hero');
  const heroWaves  = document.querySelector('.hero__waves');
  const heroGlow   = document.querySelector('.hero__glow');
  const heroInner  = document.querySelector('.hero .wrap');
  let parking = false;
  const parallax = () => {
    const y = window.scrollY;
    const h = hero.offsetHeight || 1;
    if (y <= h) {
      const p = y / h;
      if (heroWaves) heroWaves.style.transform = `translate3d(0, ${y * 0.28}px, 0)`;
      if (heroGlow)  heroGlow.style.transform  = `translate3d(0, ${y * 0.16}px, 0)`;
      if (heroInner) {
        heroInner.style.transform = `translate3d(0, ${y * 0.18}px, 0)`;
        heroInner.style.opacity = String(Math.max(0, 1 - p * 1.05));
      }
    }
    parking = false;
  };
  window.addEventListener('scroll', () => {
    if (!parking) { requestAnimationFrame(parallax); parking = true; }
  }, { passive: true });
  parallax();
}

/* -- Stats count-up when the strip scrolls into view -- */
function countUp(elTarget){
  const to  = parseInt(elTarget.dataset.to, 10);
  const pre = elTarget.dataset.prefix || '';
  const suf = elTarget.dataset.suffix || '';
  const render = (v) => {
    elTarget.innerHTML = (pre ? `<span>${pre}</span>` : '') + v + (suf ? `<span>${suf}</span>` : '');
  };
  if (reduceMotion) { render(to); return; }
  const dur = 1500, start = performance.now();
  const step = (now) => {
    const p = Math.min(1, (now - start) / dur);
    const eased = 1 - Math.pow(1 - p, 3);   // easeOutCubic
    render(Math.round(to * eased));
    if (p < 1) requestAnimationFrame(step);
  };
  requestAnimationFrame(step);
}

const statsEl = document.getElementById('stats');
if (statsEl) {
  const statNums = statsEl.querySelectorAll('.num[data-to]');
  const statObserver = new IntersectionObserver((entries, obs) => {
    entries.forEach(en => {
      if (en.isIntersecting) { statNums.forEach(countUp); obs.disconnect(); }
    });
  }, { threshold: 0.4 });
  statObserver.observe(statsEl);
}

/* Graceful fallback: if any thumbnail fails to load, hide its tile/item
   rather than showing a broken-image icon. */
document.addEventListener('error', e => {
  const img = e.target;
  if (img.tagName !== 'IMG') return;
  const host = img.closest('.tile, .gitem');
  if (host) host.style.display = 'none';
}, true);
